---
title: "Hello, Python"
date: "2026-04-15"
format:
  gfm: default
  html:
    code-fold: true
    code-summary: "Click here to see Python code"
execute:
  echo: true
---

## A Basic Python Program

In Python, we do not need to declare the data type before we assign value
to a variable. And we can even change tha data type by reassign value to the variable, like a string ot a boolean.

Comments in Python begins with #.

```{python}
spam_amount = 0 
# Here we create a var called spam_amout 
# And assign it the value of 0 using =
# = is called an assignment operator

print(spam_amount)
# print() is a python function that we can display the value of a variable

spam_amount = spam_amount + 4
# Here we reassign the value to spam_account, where new_value = old_value + 4(0+4=4)

if spam_amount > 0:
    # the colon(:) indicates that there is a new code block is starting
    # this means that:
    # if the condition is true,
    # then run the new code block
    print("But I don't want ANY spam!")
    # Here 4>0 is true, then we run the new code block
    # This is a String, which can be marked by "" or  ''

viking_song = "Spam " * spam_amount
# * operator can be used to multiply 2 numbers
# We can also use * to multiply a string by a number to repeat it many times, same as + operator.
print(viking_song)
```

# Numbers and arithmetic in Python

When we meet a var in Python, we can ask Python the data type by using type() function.

In Python, we have lots of data types.

1. int : integer
```{python}
var = 0
type(var) # Here the output is int.
```

2. float : floating point number
```{python}
var = 0.0
type(var) # Here the output is float.
```

3. bool : boolean(True/False)
```{python}
var = True
type(var) # Here the output is bool.  
```

A natural thing we want to do with numbers is arithmetic.
In Python, we have lots of operators for arithmetic.

a+b addition
a-b subtraction
a*b multiplication
a/b division
a//b floor division
a%b modulus
a**b exponentiation
-a negation

An intersting observation is that Python gives us 2 types of division.
```{python}
print(5 / 2) # 2.5
print(6 / 2) # 3.0
# The interesting thing is that the data type is float.

print(5 // 2) # 2
print(6 // 2) # 3
# // operator give us the int type
```

## Order of operations

括号 (Parentheses)、指数 (Exponents)、乘法/除法 (Multiplication/Division)、加法/减法 (Addition/Subtraction)。

```{python}
print(8 / 2 - 3 + 2) 
# The result is 3.0 (float) not 3 (int).
print(- 3 + 4 * 2)

hat_height_cm = 25
my_height_cm = 190
# How tall am I, in meters, when wearing my hat?    
total_hat_meters = (hat_height_cm + my_height_cm) / 100
print("Height in meters =", total_hat_meters)
```

## Builtin functions for working with numbers

min and max function reture the minimum and maximum of their arguments.

```{python}
print(min(1, 2, 3)) #1
print(max(1, 2, 3)) #3
```

abs function returns the absolute value of it argument.

```{python}
print(abs(32)) #32
print(abs(-32)) #32
```

int() and float() and convert numbers into corresponding tyoe.
```{python}
print(float(10)) #10.0
print(int(3.33)) #3
```
